# fly.toml file generated for chantzish on 2022-09-06T10:08:21+03:00

app = "chantzish"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  APP_NAME="chantzish"
  AUTH_KEYS="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpQbtDyDDhGwUDexAttZlT+pw4vnqcQeLAyg+f8Rzf9mhO2lD1/OcTakj6o1x7RpB+kWU3v0b8Z+RggJYJl02T9kDw9T9bw33Oj80d6mGFqgK3CyAAHRfda6VAQC220LbhgiOfUuTByHrEDGGpSwEF8pcIP9/W5Cm3x4ygiUhEw5vTm0VeywS+PS5338pWA8c6RQXlzVLLqSg6VSpjy0pHn8v65Fait6boRIj94UmizBEbavG255YztKlBh8WpSoCjoyMuz987rNKpqplerlqPzVxStKzkZ3eZwGf49k0H+/6z5w086DBJMFx360IIKzLZ5LD1yEhbKrEDRrIycKOV"
  GIT_CONF='''
[user]
	email = chantzish@gmail.com
	name = chantzish
[credential]
	helper = store
[color]
	ui = auto'''
  GIT_EMAIL="chantzish@gmail.com"
  GIT_NAME="chantzish"
  LAUNCH_RUNTIME='''
# adding swap
echo 1234 | sudo -S fallocate -l 1G /swapfile
echo 1234 | sudo -S chmod 600 /swapfile 
echo 1234 | sudo -S mkswap /swapfile 
echo 1234 | sudo -S swapon /swapfile

export HOME=/home/user
export USER=`whoami`
export LANG=en_US.UTF-8
export PATH="$PATH:/home/user/.local/bin:/usr/games:/usr/local/games"
export SHELL=/usr/bin/bash

touch /opt/noVNC/`whoami`

cd /opt/noVNC && ./utils/novnc_proxy --listen 6080 --vnc localhost:5901 --heartbeat 30 &
printf "%s" "$AUTH_KEYS" > .ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
echo 1234 | sudo -S mkdir -p /run/sshd
/opt/noVNC/utils/websockify/run 6090 localhost:2200 --heartbeat=45 &
echo 1234 | sudo -S /usr/sbin/sshd -p 2200 -o AuthorizedKeysFile=/home/user/.ssh/authorized_keys &

#cd ~
# fix according to site
#echo '#!/bin/sh\n\nwhile :; do wget '$APP_NAME'.herokuapp.com -q -O /dev/null -o /dev/null; sleep 4m; done &' | tee .local/bin/stop.sh
#chmod +x .local/bin/stop.sh


#mkdir -m 1777 /tmp/.X11-unix
mkdir -p .vnc
printf "%s" "$VNC_PASS" | vncpasswd -f > /home/user/.vnc/passwd
chmod 600 /home/user/.vnc/passwd
printf "%s\n" "$XSTARTUP" > .vnc/xstartup
chmod +x .vnc/xstartup

printf "%s" "$IDENTITY" > .ssh/id_rsa
chmod 600 .ssh/id_rsa
printf "%s" "$GDRIVE_TOKEN" > .gdrive/token_v2.json
gdrive download $TELEGRAM_LOCAL
tar zxf telegram.local.tar.gz
rm -rf /opt/Telegram
wget -q -O- https://updates.tdesktop.com/tlinux/tsetup.4.1.1.tar.xz | tar xJ -C /opt/
printf "%s" "$GIT_CONF" > .gitconfig
git config --global user.email "$GIT_EMAIL"
git config --global user.name "$GIT_NAME"
git config --global credential.helper store
git config --global color.ui auto
printf "%s" "$GIT_CREDENTIALS" > .git-credentials
mkdir -p /home/user/.config/transmission
printf "%s" "$TRANSMISSION_SETTINGS" > /home/user/.config/transmission/settings.json
touch ~/.Xauthority
#xauth generate $DISPLAY . trusted
vncserver -geometry 1536x754 :1
'''
  PORT=80
  TRANSMISSION_SETTINGS='''
{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-updates-enabled": true,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "compact-view": false,
    "details-window-height": 500,
    "details-window-width": 700,
    "dht-enabled": true,
    "download-dir": "/home/user/Downloads",
    "download-queue-enabled": true,
    "download-queue-size": 5,
    "encryption": 1,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/home/user/Downloads",
    "incomplete-dir-enabled": false,
    "inhibit-desktop-hibernation": false,
    "lpd-enabled": false,
    "main-window-height": 500,
    "main-window-is-maximized": 0,
    "main-window-width": 563,
    "main-window-x": 50,
    "main-window-y": 50,
    "message-level": 2,
    "open-dialog-dir": "/home/user",
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": true,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 2,
    "ratio-limit-enabled": false,
    "rename-partial-files": true,
    "rpc-authentication-required": false,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": false,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": true,
    "rpc-password": "{acc867eca6dbdbd868ebf900e8a4898c27a70167sn8e0.9.",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "",
    "rpc-whitelist": "127.0.0.1,::1",
    "rpc-whitelist-enabled": true,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "show-backup-trackers": false,
    "show-extra-peer-details": false,
    "show-filterbar": true,
    "show-notification-area-icon": false,
    "show-options-window": true,
    "show-statusbar": true,
    "show-toolbar": true,
    "show-tracker-scrapes": false,
    "sort-mode": "sort-by-name",
    "sort-reversed": false,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "statusbar-stats": "total-ratio",
    "torrent-added-notification-enabled": true,
    "torrent-complete-notification-enabled": true,
    "torrent-complete-sound-command": "canberra-gtk-play -i complete-download -d 'transmission torrent downloaded'",
    "torrent-complete-sound-enabled": true,
    "trash-can-enabled": true,
    "trash-original-torrent-files": false,
    "umask": 18,
    "upload-slots-per-torrent": 14,
    "user-has-given-informed-consent": true,
    "utp-enabled": true,
    "watch-dir": "/home/user/Downloads",
    "watch-dir-enabled": false
}
'''
  XSTARTUP='''
export HOME=/home/user
export USER=`whoami`
export LANG=en_US.UTF-8
export PATH="$PATH:/home/user/.local/bin:/usr/games:/usr/local/games"
export SHELL=/usr/bin/bash

vncconfig -nowin &
/usr/bin/lxsession -s Lubuntu
'''

[experimental]
  allowed_public_ports = []
  auto_rollback = true


#[[services]]
#  internal_port = 2200
#  protocol = "tcp"

#  [[services.ports]]
#    port = "5000"

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

