#!/bin/sh

export HOME=/home/user
export USER=`whoami`
export LANG=en_US.UTF-8
export PATH="$PATH:/home/user/.local/bin:/usr/games:/usr/local/games"
export SHELL=/usr/bin/bash
/usr/bin/lxsession -s Lubuntu &
vncconfig -nowin &
